sudo: enabled

env:
  - ELASTIC_VERSION=6.4.2

services:
  - docker

script:
- docker pull docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
- docker tag docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION  $DOCKER_USERNAME/elasticsearch:$ELASTIC_VERSION
- docker images
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $DOCKER_USERNAME/elasticsearch:$ELASTIC_VERSION
