sudo: enabled
language: python
python:
  - "3.6"

services:
  - docker

script:
- pip install requests
- ELASTIC_VERSION=$(python get_version.py)
- docker pull docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
- docker tag docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION  $DOCKER_USERNAME/elasticsearch:$ELASTIC_VERSION
- docker images
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
- docker push $DOCKER_USERNAME/elasticsearch:$ELASTIC_VERSION
