sudo: enabled
language: python
python:
  - "3.6"

services:
  - docker

script:
- pip install requests
- ELASTIC_VERSION=$(python get_version.py)
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
# pull and push Elasticsearch
- docker pull docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION
- docker images
- docker tag docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION  $DOCKER_USERNAME/elasticsearch:$ELASTIC_VERSION
- docker push $DOCKER_USERNAME/elasticsearch:$ELASTIC_VERSION
- docker tag docker.elastic.co/elasticsearch/elasticsearch:$ELASTIC_VERSION  $DOCKER_USERNAME/elasticsearch:latest
- docker push $DOCKER_USERNAME/elasticsearch:latest
- docker rmi -f $(docker images -q)
# pull and push Kibana
- docker pull docker.elastic.co/kibana/kibana:$ELASTIC_VERSION
- docker images
- docker tag docker.elastic.co/kibana/kibana:$ELASTIC_VERSION  $DOCKER_USERNAME/kibana:$ELASTIC_VERSION
- docker push $DOCKER_USERNAME/kibana:$ELASTIC_VERSION
- docker tag docker.elastic.co/kibana/kibana:$ELASTIC_VERSION  $DOCKER_USERNAME/kibana:latest
- docker push $DOCKER_USERNAME/kibana:latest
- docker rmi -f $(docker images -q)
# pull and push Logstash
- docker pull docker.elastic.co/logstash/logstash:$ELASTIC_VERSION
- docker images
- docker tag docker.elastic.co/logstash/logstash:$ELASTIC_VERSION  $DOCKER_USERNAME/logstash:$ELASTIC_VERSION
- docker push $DOCKER_USERNAME/logstash:$ELASTIC_VERSION
- docker tag docker.elastic.co/logstash/logstash:$ELASTIC_VERSION  $DOCKER_USERNAME/logstash:latest
- docker push $DOCKER_USERNAME/logstash:latest
- docker rmi -f $(docker images -q)
# pull and push APM Server
- docker pull docker.elastic.co/apm/apm-server:$ELASTIC_VERSION
- docker images
- docker tag docker.elastic.co/apm/apm-server:$ELASTIC_VERSION  $DOCKER_USERNAME/apm-server:$ELASTIC_VERSION
- docker push $DOCKER_USERNAME/apm-server:$ELASTIC_VERSION
- docker tag docker.elastic.co/apm/apm-server:$ELASTIC_VERSION  $DOCKER_USERNAME/apm-server:latest
- docker push $DOCKER_USERNAME/apm-server:latest
- docker rmi -f $(docker images -q)
# pull and push Beats
# pull and push Filebeat
- docker pull docker.elastic.co/beats/filebeat:$ELASTIC_VERSION
- docker images
- docker tag docker.elastic.co/beats/filebeat:$ELASTIC_VERSION  $DOCKER_USERNAME/filebeat:$ELASTIC_VERSION
- docker push $DOCKER_USERNAME/filebeat:$ELASTIC_VERSION
- docker tag docker.elastic.co/beats/filebeat:$ELASTIC_VERSION  $DOCKER_USERNAME/filebeat:latest
- docker push $DOCKER_USERNAME/filebeat:latest
- docker rmi -f $(docker images -q)
# pull and push Metricbeat
- docker pull docker.elastic.co/beats/metricbeat:$ELASTIC_VERSION
- docker images
- docker tag docker.elastic.co/beats/metricbeat:$ELASTIC_VERSION  $DOCKER_USERNAME/metricbeat:$ELASTIC_VERSION
- docker push $DOCKER_USERNAME/metricbeat:$ELASTIC_VERSION
- docker tag docker.elastic.co/beats/metricbeat:$ELASTIC_VERSION  $DOCKER_USERNAME/metricbeat:latest
- docker push $DOCKER_USERNAME/metricbeat:latest
- docker rmi -f $(docker images -q)
# pull and push Packetbeat
- docker pull docker.elastic.co/beats/packetbeat:$ELASTIC_VERSION
- docker images
- docker tag docker.elastic.co/beats/packetbeat:$ELASTIC_VERSION  $DOCKER_USERNAME/packetbeat:$ELASTIC_VERSION
- docker push $DOCKER_USERNAME/packetbeat:$ELASTIC_VERSION
- docker tag docker.elastic.co/beats/packetbeat:$ELASTIC_VERSION  $DOCKER_USERNAME/packetbeat:latest
- docker push $DOCKER_USERNAME/packetbeat:latest
- docker rmi -f $(docker images -q)
# pull and push Heartbeat
- docker pull docker.elastic.co/beats/heartbeat:$ELASTIC_VERSION
- docker images
- docker tag docker.elastic.co/beats/heartbeat:$ELASTIC_VERSION  $DOCKER_USERNAME/heartbeat:$ELASTIC_VERSION
- docker push $DOCKER_USERNAME/heartbeat:$ELASTIC_VERSION
- docker tag docker.elastic.co/beats/heartbeat:$ELASTIC_VERSION  $DOCKER_USERNAME/heartbeat:latest
- docker push $DOCKER_USERNAME/heartbeat:latest
- docker rmi -f $(docker images -q)
# pull and push Auditbeat
- docker pull docker.elastic.co/beats/auditbeat:$ELASTIC_VERSION
- docker images
- docker tag docker.elastic.co/beats/auditbeat:$ELASTIC_VERSION  $DOCKER_USERNAME/auditbeat:$ELASTIC_VERSION
- docker push $DOCKER_USERNAME/auditbeat:$ELASTIC_VERSION
- docker tag docker.elastic.co/beats/auditbeat:$ELASTIC_VERSION  $DOCKER_USERNAME/auditbeat:latest
- docker push $DOCKER_USERNAME/auditbeat:latest
- docker rmi -f $(docker images -q)
